# Use Node image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install global Angular CLI
RUN npm install -g @angular/cli

# Copy package files first for caching
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Expose Angular dev server port
EXPOSE 4200

# Start Angular dev server
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll=2000", "--disable-host-check"]
